name: CI tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run Tests
        run: |
          npm i
          npm run coverage
