name: CI tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run Tests
        run: |
          npm i
          npm run test

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1

      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
